# Clock Signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# Reset and Go signals
set_property PACKAGE_PIN R2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN T1 [get_ports go]
set_property IOSTANDARD LVCMOS33 [get_ports go]

# Data Inputs (data_sel_1 and data_sel_2)
set_property PACKAGE_PIN V17 [get_ports {data_sel_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_1[0]}]
set_property PACKAGE_PIN V16 [get_ports {data_sel_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_1[1]}]
set_property PACKAGE_PIN W16 [get_ports {data_sel_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_1[2]}]
set_property PACKAGE_PIN W17 [get_ports {data_sel_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_1[3]}]
set_property PACKAGE_PIN W15 [get_ports {data_sel_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_1[4]}]
set_property PACKAGE_PIN V15 [get_ports {data_sel_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_1[5]}]
set_property PACKAGE_PIN W14 [get_ports {data_sel_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_1[6]}]

set_property PACKAGE_PIN W13 [get_ports {data_sel_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_2[0]}]
set_property PACKAGE_PIN V2 [get_ports {data_sel_2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_2[1]}]
set_property PACKAGE_PIN T3 [get_ports {data_sel_2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_2[2]}]
set_property PACKAGE_PIN T2 [get_ports {data_sel_2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_2[3]}]
set_property PACKAGE_PIN R3 [get_ports {data_sel_2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_2[4]}]
set_property PACKAGE_PIN W2 [get_ports {data_sel_2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_2[5]}]
set_property PACKAGE_PIN U1 [get_ports {data_sel_2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_sel_2[6]}]

# Output GCD Result
set_property PACKAGE_PIN U16 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property PACKAGE_PIN E19 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property PACKAGE_PIN U19 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property PACKAGE_PIN V19 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property PACKAGE_PIN W18 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property PACKAGE_PIN U15 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property PACKAGE_PIN U14 [get_ports {out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]

# Done Signal
set_property PACKAGE_PIN V14 [get_ports done]
set_property IOSTANDARD LVCMOS33 [get_ports done]
